/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace StateProofVerifier {
  export type SlotValueStruct = {
    exists: PromiseOrValue<boolean>;
    value: PromiseOrValue<BigNumberish>;
  };

  export type SlotValueStructOutput = [boolean, BigNumber] & {
    exists: boolean;
    value: BigNumber;
  };
}

export interface IRootsWarehouseInterface extends utils.Interface {
  functions: {
    "getStorage(address,bytes32,bytes32,bytes)": FunctionFragment;
    "processStorageRoot(address,bytes32,bytes,bytes)": FunctionFragment;
    "storageRoots(address,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getStorage" | "processStorageRoot" | "storageRoots"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getStorage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "processStorageRoot",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "storageRoots",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "getStorage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processStorageRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storageRoots",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRootsWarehouse extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRootsWarehouseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getStorage(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      slot: PromiseOrValue<BytesLike>,
      storageProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[StateProofVerifier.SlotValueStructOutput]>;

    processStorageRoot(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      blockHeaderRLP: PromiseOrValue<BytesLike>,
      accountStateProofRLP: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    storageRoots(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getStorage(
    account: PromiseOrValue<string>,
    blockHash: PromiseOrValue<BytesLike>,
    slot: PromiseOrValue<BytesLike>,
    storageProof: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<StateProofVerifier.SlotValueStructOutput>;

  processStorageRoot(
    account: PromiseOrValue<string>,
    blockHash: PromiseOrValue<BytesLike>,
    blockHeaderRLP: PromiseOrValue<BytesLike>,
    accountStateProofRLP: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  storageRoots(
    account: PromiseOrValue<string>,
    blockHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getStorage(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      slot: PromiseOrValue<BytesLike>,
      storageProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<StateProofVerifier.SlotValueStructOutput>;

    processStorageRoot(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      blockHeaderRLP: PromiseOrValue<BytesLike>,
      accountStateProofRLP: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    storageRoots(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getStorage(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      slot: PromiseOrValue<BytesLike>,
      storageProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    processStorageRoot(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      blockHeaderRLP: PromiseOrValue<BytesLike>,
      accountStateProofRLP: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    storageRoots(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getStorage(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      slot: PromiseOrValue<BytesLike>,
      storageProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    processStorageRoot(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      blockHeaderRLP: PromiseOrValue<BytesLike>,
      accountStateProofRLP: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    storageRoots(
      account: PromiseOrValue<string>,
      blockHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
