/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IL1VotingStrategy,
  IL1VotingStrategyInterface,
} from "../IL1VotingStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getFullPropositionPower",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getFullVotingPower",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IL1VotingStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IL1VotingStrategyInterface {
    return new utils.Interface(_abi) as IL1VotingStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL1VotingStrategy {
    return new Contract(address, _abi, signerOrProvider) as IL1VotingStrategy;
  }
}
