/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IVotingPortal, IVotingPortalInterface } from "../IVotingPortal";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "snapshotBlockhash",
        type: "bytes32",
      },
      {
        internalType: "uint24",
        name: "votingDuration",
        type: "uint24",
      },
    ],
    name: "initializeVoting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVotingPortal__factory {
  static readonly abi = _abi;
  static createInterface(): IVotingPortalInterface {
    return new utils.Interface(_abi) as IVotingPortalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVotingPortal {
    return new Contract(address, _abi, signerOrProvider) as IVotingPortal;
  }
}
