import type { NextPage } from "next";
import Head from "next/head";
import { WalletList } from "../src/web3/components/WalletList";
import styles from "../styles/Home.module.css";
import {useStore} from '../src/store';
import {useEffect} from 'react';

const Home: NextPage = () => {
  const getAAVEBalances = useStore(store => store.getAAVEBalances);
  const aaveBalances = useStore(store => store.aaveBalances);

  const getVotedInfo = useStore(store => store.getVotedInfo);
  const votedInfo = useStore(store => store.votedInfo);

  const getVoters = useStore(store => store.getVoters);
  const voters = useStore(store => store.voters);

  useEffect(() => {
    getAAVEBalances();
    getVotedInfo();
    getVoters();
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WalletList />


      <ul>
        {aaveBalances.map((balance, index) => <li key={index}>{balance}</li>)}
      </ul>

      <div>
        <h2>Voted info</h2>
        <hr/>
        <p>support: {votedInfo.support ? 'yes' : 'no'}</p>
        <p>voted balance: {votedInfo.votedPower}</p>
      </div>

      <ul>
        {voters.map((voter) => <li key={voter.proposalId}>{voter.address}</li>)}
      </ul>
    </div>
  );
};

export default Home;
